import Foundation

/// The web sim's live state, polled from `live_sim_state` so the phone mirrors it.
struct LiveSimState: Equatable {
    var hole: Int?
    var par: Int?
    var yards: Int?
    var holeName: String?
    var stroke: Int?
    var toPar: Int?
    var distanceToPinYards: Int?
    var simState: String?
    var lastShot: LiveShot?

    struct LiveShot: Codable, Equatable {
        var carryYards: Double?
        var totalYards: Double?
        var lie: String?
        var result: String?
    }
}

extension LiveSimState: Codable {
    enum CodingKeys: String, CodingKey {
        case hole, par, yards, stroke
        case holeName = "hole_name"
        case toPar = "to_par"
        case distanceToPinYards = "distance_to_pin_yards"
        case simState = "sim_state"
        case lastShot = "last_shot"
    }
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        hole = try? c.decode(Int.self, forKey: .hole)
        par = try? c.decode(Int.self, forKey: .par)
        yards = try? c.decode(Int.self, forKey: .yards)
        holeName = try? c.decode(String.self, forKey: .holeName)
        stroke = try? c.decode(Int.self, forKey: .stroke)
        toPar = try? c.decode(Int.self, forKey: .toPar)
        // numeric may arrive as Int, Double, or a precision-preserving String
        if let i = try? c.decode(Int.self, forKey: .distanceToPinYards) { distanceToPinYards = i }
        else if let d = try? c.decode(Double.self, forKey: .distanceToPinYards) { distanceToPinYards = Int(d) }
        else if let s = try? c.decode(String.self, forKey: .distanceToPinYards), let d = Double(s) { distanceToPinYards = Int(d) }
        else { distanceToPinYards = nil }
        simState = try? c.decode(String.self, forKey: .simState)
        lastShot = try? c.decode(LiveShot.self, forKey: .lastShot)
    }
}

// Broadcasts shot data to a browser-based sim session via Supabase Realtime,
// and polls the sim's live state back so the phone can mirror it.
// Uses only the anon (publishable) key — never the service-role key.
// The session code is generated by the website and typed into the app by the user.
@MainActor
final class LiveSimService: ObservableObject {
    @Published var enteredCode: String = "" {
        didSet {
            let digits = String(enteredCode.filter(\.isNumber).prefix(6))
            if digits != enteredCode { enteredCode = digits; return }
            // Only reset connection state when the actual 6-digit code changes.
            // Avoids double-reset from SwiftUI re-firing didSet on focus changes.
            let prevDigits = String(oldValue.filter(\.isNumber).prefix(6))
            if digits != prevDigits {
                shotsSent = 0
                lastBroadcastError = nil
                isConnectedToSim = false
                lastShot = nil
                lastShotAt = nil
                bestCarryYards = 0
                topBallSpeedMph = 0
                liveState = nil
                stopPolling()
            }
        }
    }
    @Published private(set) var isBroadcasting = false
    @Published private(set) var isConnectedToSim = false
    @Published private(set) var lastBroadcastError: String?
    @Published private(set) var shotsSent = 0

    // Live session telemetry — fuels the connected-state UI.
    @Published private(set) var lastShot: SavedShotMetrics?
    @Published private(set) var bestCarryYards: Double = 0
    @Published private(set) var topBallSpeedMph: Double = 0
    @Published private(set) var lastShotAt: Date?

    // Mirrored sim state (current hole / shot result / score), polled while connected.
    @Published private(set) var liveState: LiveSimState?
    private var pollTask: Task<Void, Never>?

    private let config: SupabaseConfig?

    init() {
        self.config = SupabaseConfig.load()
    }

    var isReadyToConnect: Bool { enteredCode.count == 6 }

    /// Sends a ping to the website so it advances from the code screen to the course selector.
    /// Only marks the session connected if the broadcast actually went through.
    func connect() async {
        guard isReadyToConnect else { return }
        isBroadcasting = true
        defer { isBroadcasting = false }
        lastBroadcastError = nil
        let ok = await broadcastRaw(event: "ping", payload: [:])
        isConnectedToSim = ok
        if ok {
            startPolling()
        } else if lastBroadcastError == nil {
            lastBroadcastError = "Couldn't reach the sim — check Wi-Fi and the code."
        }
    }

    /// Drops the current pairing so the user can re-enter / change the code.
    func disconnect() {
        isConnectedToSim = false
        lastBroadcastError = nil
        stopPolling()
        liveState = nil
    }

    // MARK: - Live state polling (web sim → phone mirror)

    private func startPolling() {
        pollTask?.cancel()
        pollTask = Task { [weak self] in
            while !Task.isCancelled {
                await self?.pollLiveState()
                try? await Task.sleep(nanoseconds: 1_200_000_000)
            }
        }
    }

    private func stopPolling() {
        pollTask?.cancel()
        pollTask = nil
    }

    private func pollLiveState() async {
        guard let config, isReadyToConnect else { return }
        var comps = URLComponents(
            url: config.baseURL.appendingPathComponent("rest/v1/live_sim_state"),
            resolvingAgainstBaseURL: false)!
        comps.queryItems = [
            URLQueryItem(name: "code", value: "eq.\(enteredCode)"),
            URLQueryItem(name: "select", value: "*"),
        ]
        guard let url = comps.url else { return }
        var req = URLRequest(url: url)
        req.setValue(config.anonKey, forHTTPHeaderField: "apikey")
        req.setValue("Bearer \(config.anonKey)", forHTTPHeaderField: "Authorization")
        req.timeoutInterval = 5
        do {
            let (data, resp) = try await URLSession.shared.data(for: req)
            guard (resp as? HTTPURLResponse)?.statusCode == 200 else { return }
            let rows = try JSONDecoder().decode([LiveSimState].self, from: data)
            if let s = rows.first { liveState = s }
        } catch {
            // best effort — keep the last known state on a transient failure
        }
    }

    /// Tells the website which club is currently selected.
    func broadcastClub(_ clubName: String) async {
        guard isConnectedToSim else { return }
        await broadcastRaw(event: "club", payload: ["clubName": clubName])
    }

    func broadcast(metrics: SavedShotMetrics) async {
        guard isReadyToConnect else {
            lastBroadcastError = "Enter the 6-digit code shown on screen"
            return
        }

        isBroadcasting = true
        defer { isBroadcasting = false }

        let payload: [String: Any] = [
            "ballSpeedMph": metrics.ballSpeedMph,
            "carryYards":   metrics.carryYards,
            "totalYards":   metrics.totalYards,
            "vlaDegrees":   metrics.vlaDegrees,
            "backspinRpm":  metrics.backspinRpm,
            "sidespinRpm":  metrics.sidespinRpm,
            "hlaDegrees":   metrics.hlaDegrees,
            "hlaDirection": metrics.sidespinRpm >= 0 ? "right" : "left",
            "smashFactor":  metrics.smashFactor,
        ]

        let ok = await broadcastRaw(event: "shot", payload: payload)
        if ok {
            lastBroadcastError = nil
            shotsSent += 1
            lastShot = metrics
            lastShotAt = Date()
            bestCarryYards = max(bestCarryYards, metrics.carryYards)
            topBallSpeedMph = max(topBallSpeedMph, metrics.ballSpeedMph)
        }
    }

    // MARK: - Private

    @discardableResult
    private func broadcastRaw(event: String, payload: [String: Any]) async -> Bool {
        guard let config else { return false }

        let body: [String: Any] = [
            "messages": [[
                "topic":   "tc-sim-\(enteredCode)",
                "event":   event,
                "payload": payload,
            ]],
        ]
        guard let bodyData = try? JSONSerialization.data(withJSONObject: body) else { return false }

        var req = URLRequest(url: config.baseURL.appendingPathComponent("realtime/v1/api/broadcast"))
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        // Authorize with the anon (publishable) key — same as the web sim client.
        // A signed-in user's access token can be expired, which 401s the broadcast
        // and silently breaks pairing; the public broadcast channel only needs anon.
        req.setValue(config.anonKey, forHTTPHeaderField: "apikey")
        req.setValue("Bearer \(config.anonKey)", forHTTPHeaderField: "Authorization")
        req.httpBody = bodyData
        req.timeoutInterval = 6   // don't hang ~60s on a flaky cellular/Wi-Fi path

        // Retry once on a transient network failure so a single dropped packet
        // doesn't lose the shot / ping.
        for attempt in 1...2 {
            do {
                let (_, response) = try await URLSession.shared.data(for: req)
                if let http = response as? HTTPURLResponse, http.statusCode >= 400 {
                    lastBroadcastError = "Broadcast failed (HTTP \(http.statusCode))"
                    return false
                }
                return true
            } catch {
                lastBroadcastError = error.localizedDescription
                if attempt == 2 { return false }
            }
        }
        return false
    }
}
